### ISSUE TITLE
ossfs内部大文件（< 1G）move返回Input/Output error

### ISSUE THREAD

**Issue by SnakeHunt2012** [ossfs-fuse/ossfs-fuse#5]
小文件没有问题，大文件4G以上会出现这种问题：

![issur 5-1](https://cloud.githubusercontent.com/assets/2970920/10938001/dfd897f0-8331-11e5-9b4a-2a1eae7d3fb7.jpg)

当文件大于1G时oss就必须使用Upload Part Copy API。当前的行为是超过5G才使用Upload Part Copy API。

![issue 5-4](https://cloud.githubusercontent.com/assets/2970920/10938458/6d8a28ae-8335-11e5-9578-4120206bc108.jpg)

**Comment by hryang** [comment]
把FIVE_GB改成ONE_GB

**Comment by SnakeHunt2012** [comment]
现在的解法是把multi-part upload/copy阀值改成1G，并且把part size改成10M（一次upload大约1s）。

**Comment by SnakeHunt2012** [comment]
设置成1G后999M的文件还是会超时，继续把multi-part upload/copy的阀值调小至100M，同时把连接OSS和读写OSS的timeout默认值改成跟s3fs一致。

connection: 10 -> 300
read/write: 30 -> 60
