### ISSUE TITLE
ossfs内部大文件（> 5G）move返回Input/Output error

### ISSUE THREAD

**Issue by SnakeHunt2012** [ossfs-fuse/ossfs-fuse#6]
![issue 5-2](https://cloud.githubusercontent.com/assets/2970920/10938064/5a576060-8332-11e5-87a1-2765491f7b16.jpg)

这里产生原因是timeout，后台观察是ossfs使用OSS的Upload Part Copy API的时候遇到timeout，这里OSS API本身的timout是60s，ossfs使用的curl的timeout设置为30。

![issue 5-3](https://cloud.githubusercontent.com/assets/2970920/10938843/37f2149c-8338-11e5-9263-e69ecefb3ae8.jpg)

**Comment by hryang** [comment]
这个场景下，期望30s上传多少数据？

**Comment by SnakeHunt2012** [comment]
5G以上使用multipart upload，每个part是500M。

这里s3fs的解决方式是吧这个默认timeout从30s调到300s：
https://github.com/s3fs-fuse/s3fs-fuse/pull/167

我们可以把超时改大，也可以把part调小。目前oss这边multipart copy/upload的量级是10M/s，所以这个刚好50s。

**Comment by SnakeHunt2012** [comment]
现在的解法是把multi-part upload/copy阀值改成1G，并且把part size改成10M（一次upload大约1s）。
